# Generated by Django 5.1.4 on 2024-12-22 12:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('imageviewer', '0002_alter_image_image_path'),
    ]

    operations = [
        migrations.CreateModel(
            name='CommutationTable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='imageviewer.image')),
                ('tag_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='imageviewer.tag')),
            ],
        ),
    ]
