# Generated by Django 5.1.4 on 2024-12-22 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('imageviewer', '0003_commutationtable'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commutationtable',
            name='image_id',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='commutationtable',
            name='tag_id',
            field=models.IntegerField(),
        ),
    ]
