# Generated by Django 5.1.4 on 2025-01-09 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('imageviewer', '0004_alter_commutationtable_image_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='thumbnail_path',
            field=models.ImageField(default=None, upload_to='thumbnails/'),
        ),
        migrations.AlterField(
            model_name='image',
            name='image_path',
            field=models.ImageField(upload_to=''),
        ),
    ]
