# Generated by Django 5.1.4 on 2025-01-13 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('imageviewer', '0005_image_thumbnail_path_alter_image_image_path'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='fake_id',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
